title: welcome to my webpage
author: GitHub User
email: gj@email.invalid
description: > # this means to ignore newlines until "baseurl:"
  just trying out github pages

# social links
twitter_username: notavailabe # DO NOT include the @ character, or else the build will fail!
github_username:  RealGJ # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
